language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coverage python-coveralls
script: nosetests tests/unit --cover-erase --with-coverage --cover-package skinflint
after_success: coveralls
